apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-batcher
  labels:
    app: spring-batcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-batcher
  template:
    metadata:
      labels:
        app: spring-batcher
    spec:
      containers:
        - name: spring-batcher-container
          image: murlidhar/spring-batcher:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-batcher-svc
spec:
  selector:
    app: spring-batcher
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080